//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilEv.UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YesilEvEntities : DbContext
    {
        public YesilEvEntities()
            : base("name=YesilEvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AramaGecmisi> AramaGecmisis { get; set; }
        public virtual DbSet<Duzenleme> Duzenlemes { get; set; }
        public virtual DbSet<Favoriler> Favorilers { get; set; }
        public virtual DbSet<FavoriListe> FavoriListes { get; set; }
        public virtual DbSet<KaraListe> KaraListes { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Uretici> Ureticis { get; set; }
        public virtual DbSet<Urun> Uruns { get; set; }
        public virtual DbSet<Uye> Uyes { get; set; }
    }
}
