//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilEv.UI
{
    using System;
    using System.Collections.Generic;
    using YesilEv.UI.DTO;

    public partial class Urun
    {
        private UrunDTO urunDTO;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Duzenlemes = new HashSet<Duzenleme>();
            this.Favorilers = new HashSet<Favoriler>();
            this.KaraListes = new HashSet<KaraListe>();
        }

        public Urun(UrunDTO urunDTO)
        {
            this.urunDTO = urunDTO;
        }

        public int ID { get; set; }
        public string BarkodNo { get; set; }
        public Nullable<int> UreticiID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public string UrunIcerik { get; set; }
        public string OnYuz { get; set; }
        public string ArkaYuz { get; set; }
        public string TakipNo { get; set; }
        public Nullable<bool> DuzenlendiMi { get; set; }
        public Nullable<int> UyeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duzenleme> Duzenlemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favoriler> Favorilers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KaraListe> KaraListes { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Uretici Uretici { get; set; }
        public virtual Uye Uye { get; set; }
        public virtual Uye Uye1 { get; set; }
    }
}
